config/routes.rb
Colchonet::Application.routes.draw do
  LOCALES ||= /en|es|pt\-BR/ 

  devise_for :admins
  
  # Site  
  scope "(:locale)", locale: LOCALES do
    resources :rooms do
      resources :reviews, only: [:create, :update], module: :rooms
    end
    resources :users
  end
  
  resource :confirmation, only: [:show]
  resource :user_sessions, only: [:create, :new, :destroy]

  get '/:locale' => 'homes#index', locale: LOCALES
  root 'homes#index'

  # Admin
  namespace :admin do
    resources :rooms
    resources :users, except: [:create, :new]
    get "about" => "dashboards#about"
    root to: "dashboards#index"
  end
end

app/models/room.rb
class Room < ActiveRecord::Base
  extend FriendlyId

  has_many :reviews, dependent: :destroy
  has_many :reviewed_rooms, through: :reviews, source: :room
  belongs_to :user
  
  validates :title, length: { minimum: 5 }, presence: true
  validates :location, length: { minimum: 5 }, presence: true
  validates :description, length: { minimum: 10 }, presence: true
  validates :slug, presence: true

  mount_uploader :picture, PictureUploader
  friendly_id :title, use: [:slugged, :history]
    
  scope :most_recent, -> { order(id: :desc) }
  
  def complete_name
    "##{id} #{title}, #{location}"
  end

  def self.search(query)
    if query.present?
      where(['location LIKE :query OR title LIKE :query OR description LIKE :query', query: "%#{query}%"])
    else
      all
    end
  end

end

app/controllers/admin/rooms_controller.rb
class Admin::RoomsController < Admin::BaseAdminController
  before_action :set_admin_room, only: [:show, :edit, :update, :destroy]

  PER_PAGE = 10

  # GET /admin/rooms
  # GET /admin/rooms.json
  def index
    @admin_rooms = Admin::Room.page(params[:page]).per(PER_PAGE)
  end

  # GET /admin/rooms/1
  # GET /admin/rooms/1.json
  def show
  end

  # GET /admin/rooms/new
  def new
    @admin_room = Admin::Room.new
  end

  # GET /admin/rooms/1/edit
  def edit
  end

  # POST /admin/rooms
  # POST /admin/rooms.json
  def create
    @admin_room = Admin::Room.new(admin_room_params)

    respond_to do |format|
      if @admin_room.save
        format.html { redirect_to @admin_room, notice: 'Room was successfully created.' }
        format.json { render action: 'show', status: :created, location: @admin_room }
      else
        format.html { render action: 'new' }
        format.json { render json: @admin_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/rooms/1
  # PATCH/PUT /admin/rooms/1.json
  def update
    respond_to do |format|
      if @admin_room.update(admin_room_params)
        format.html { redirect_to [:admin, @admin_room], notice: 'Room was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @admin_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/rooms/1
  # DELETE /admin/rooms/1.json
  def destroy
    @admin_room.destroy
    respond_to do |format|
      format.html { redirect_to admin_rooms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_room
      @admin_room = Admin::Room.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_room_params
      params.require(:room).permit(:title, :location, :description, :picture, :user_id)
    end
end

app/controllers/rooms/reviews_controller.rb
class Rooms::ReviewsController < ApplicationController
  before_filter :require_authentication

  def create
    begin
      review = room.reviews.
        find_or_initialize_by(user_id: current_user.id)
      review.update!(review_params)
      head :ok
    rescue
      head :not_found
    end
  end

  def update
    create
  end

  private

    def room
      @room ||= Room.friendly.where.not({ user_id: current_user.id }).find(params[:room_id])
    end

    def review_params
      params.require(:review).permit(:points)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:edit, :update, :destroy]
  before_action :require_authentication, only: [:new, :edit, :create, :update, :destroy]

  PER_PAGE = 1

  # GET /rooms
  # GET /rooms.json
  def index
    @search_query = params[:q]

    rooms = Room.search(@search_query).page(params[:page]).per(PER_PAGE)

    @rooms = RoomCollectionPresenter.new(rooms.most_recent, self)
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    room_model = Room.friendly.find(params[:id])
    @room = RoomPresenter.new(room_model, self)
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
    @room.user = current_user

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: t('flash.notice.room_created') }
        format.json { render action: 'show', status: :created, location: @room }
      else
        format.html { render action: 'new' }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: t('flash.notice.room_updated') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: t('flash.notice.room_destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = current_user.rooms.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:title, :location, :description, :picture)
    end
end

app/helpers/admin/rooms_helper.rb
module Admin::RoomsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def belongs_to_user(room)
    user_signed_in? && room.user == current_user
  end
end

app/views/admin/rooms/_form.html.erb
<%= form_for([:admin, @admin_room], :html_options => { :class => 'form', :type => 'file' }) do |f| %>
  <% if @admin_room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_room.errors.count, "error") %> prohibited this admin_room from being saved:</h2>

      <ul>
      <% @admin_room.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :user_id %><br>
    <%= f.collection_select :user_id, User.all, :id, :name_for_select, { include_blank: "Selecione" }, { :class => 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :location %><br>
    <%= f.text_field :location, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :picture %><br>
    <%= f.file_field :picture, :class => 'form-control' %>
  </div>
  <div class="form-group actions">
    <%= f.submit :class => 'btn btn-success' %>
  </div>
<% end %>

app/views/admin/rooms/edit.html.erb
<div class="page-header">
	<h1><%= t('site.editing_room') %></h1>
</div>
<%= breadcrumb %>

<%= render 'form' %>

<%= link_to '<i class="fa fa-search"></i> '.html_safe + t("site.show"), @admin_room, { :class => 'btn btn-primary' } %> 
<%= back_link admin_rooms_path %>

app/views/admin/rooms/index.html.erb
<div class="page-header">
  <h1><%= t('admin.rooms') %></h1>
</div>
<%= breadcrumb %>
<p><%= add_link(new_admin_room_path) %></p>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t('admin.user') %></th>
      <th><%= t('admin.title') %></th>
      <th><%= t('admin.location') %></th>
      <th><%= t('admin.description') %></th>
      <th><%= t('admin.picture') %></th>
      <th><%= t('admin.actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% @admin_rooms.each do |admin_room| %>
      <tr>
        <td><%= admin_room.user.full_name unless admin_room.user.nil? %></td>
        <td><%= admin_room.title %></td>
        <td><%= admin_room.location %></td>
        <td><%= admin_room.description %></td>
        <td><%= image_tag admin_room.picture.thumb %></td>
        <td>
          <%= show_link [:admin, admin_room] %>
          <%= edit_link edit_admin_room_path(admin_room) %>
          <%= destroy_link [:admin, admin_room] %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @admin_rooms %>

app/views/admin/rooms/new.html.erb
<div class="page-header">
	<h1><%= t('admin.new_room') %></h1>
</div>
<%= breadcrumb %>

<%= render 'form' %>

<%= back_link admin_rooms_path %>

app/views/admin/rooms/show.html.erb
<div class="page-header">
  <h1><%= t('admin.show_room') %></h1>
</div>
<%= breadcrumb %>

<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @admin_room.user.full_name unless @admin_room.user.nil? %>
</p>

<p>
  <strong>Title:</strong>
  <%= @admin_room.title %>
</p>

<p>
  <strong>Location:</strong>
  <%= @admin_room.location %>
</p>

<p>
  <strong>Description:</strong>
  <%= @admin_room.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag @admin_room.picture.thumb %>
</p>

<%= link_to t('admin.edit'), edit_admin_room_path(@admin_room), { :class => 'btn btn-success' } %> 
<%= back_link admin_rooms_path %>