config/routes.rb
Colchonet::Application.routes.draw do
  LOCALES ||= /en|es|pt\-BR/ 

  devise_for :admins
  
  # Site  
  scope "(:locale)", locale: LOCALES do
    resources :rooms do
      resources :reviews, only: [:create, :update], module: :rooms
    end
    resources :users
  end
  
  resource :confirmation, only: [:show]
  resource :user_sessions, only: [:create, :new, :destroy]

  get '/:locale' => 'homes#index', locale: LOCALES
  root 'homes#index'

  # Admin
  namespace :admin do
    resources :rooms
    resources :users, except: [:create, :new]
    get "about" => "dashboards#about"
    root to: "dashboards#index"
  end
end

app/models/room.rb
class Room < ActiveRecord::Base
  extend FriendlyId

  has_many :reviews, dependent: :destroy
  has_many :reviewed_rooms, through: :reviews, source: :room
  belongs_to :user
  
  validates :title, length: { minimum: 5 }, presence: true
  validates :location, length: { minimum: 5 }, presence: true
  validates :description, length: { minimum: 10 }, presence: true
  validates :slug, presence: true

  mount_uploader :picture, PictureUploader
  friendly_id :title, use: [:slugged, :history]
    
  scope :most_recent, -> { order(id: :desc) }
  
  def complete_name
    "##{id} #{title}, #{location}"
  end

  def self.search(query)
    if query.present?
      where(['location LIKE :query OR title LIKE :query OR description LIKE :query', query: "%#{query}%"])
    else
      all
    end
  end

end

app/controllers/admin/rooms_controller.rb
class Admin::RoomsController < Admin::BaseAdminController
  before_action :set_admin_room, only: [:show, :edit, :update, :destroy]

  PER_PAGE = 10

  # GET /admin/rooms
  # GET /admin/rooms.json
  def index
    @admin_rooms = Admin::Room.page(params[:page]).per(PER_PAGE)
  end

  # GET /admin/rooms/1
  # GET /admin/rooms/1.json
  def show
  end

  # GET /admin/rooms/new
  def new
    @admin_room = Admin::Room.new
  end

  # GET /admin/rooms/1/edit
  def edit
  end

  # POST /admin/rooms
  # POST /admin/rooms.json
  def create
    @admin_room = Admin::Room.new(admin_room_params)

    respond_to do |format|
      if @admin_room.save
        format.html { redirect_to @admin_room, notice: 'Room was successfully created.' }
        format.json { render action: 'show', status: :created, location: @admin_room }
      else
        format.html { render action: 'new' }
        format.json { render json: @admin_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/rooms/1
  # PATCH/PUT /admin/rooms/1.json
  def update
    respond_to do |format|
      if @admin_room.update(admin_room_params)
        format.html { redirect_to [:admin, @admin_room], notice: 'Room was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @admin_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/rooms/1
  # DELETE /admin/rooms/1.json
  def destroy
    @admin_room.destroy
    respond_to do |format|
      format.html { redirect_to admin_rooms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_room
      @admin_room = Admin::Room.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_room_params
      params.require(:room).permit(:title, :location, :description, :picture, :user_id)
    end
end

app/controllers/rooms/reviews_controller.rb
class Rooms::ReviewsController < ApplicationController
  before_filter :require_authentication

  def create
    begin
      review = room.reviews.
        find_or_initialize_by(user_id: current_user.id)
      review.update!(review_params)
      head :ok
    rescue
      head :not_found
    end
  end

  def update
    create
  end

  private

    def room
      @room ||= Room.friendly.where.not({ user_id: current_user.id }).find(params[:room_id])
    end

    def review_params
      params.require(:review).permit(:points)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:edit, :update, :destroy]
  before_action :require_authentication, only: [:new, :edit, :create, :update, :destroy]

  PER_PAGE = 1

  # GET /rooms
  # GET /rooms.json
  def index
    @search_query = params[:q]

    rooms = Room.search(@search_query).page(params[:page]).per(PER_PAGE)

    @rooms = RoomCollectionPresenter.new(rooms.most_recent, self)
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    room_model = Room.friendly.find(params[:id])
    @room = RoomPresenter.new(room_model, self)
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
    @room.user = current_user

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: t('flash.notice.room_created') }
        format.json { render action: 'show', status: :created, location: @room }
      else
        format.html { render action: 'new' }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: t('flash.notice.room_updated') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: t('flash.notice.room_destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = current_user.rooms.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:title, :location, :description, :picture)
    end
end

app/helpers/admin/rooms_helper.rb
module Admin::RoomsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def belongs_to_user(room)
    user_signed_in? && room.user == current_user
  end
end

app/views/rooms/_form.html.erb
<%= form_for(@room, :html => { :class => 'form' }) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= error_tag @room, :title %>
  </div>
  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
    <%= error_tag @room, :location %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
    <%= error_tag @room, :description %>
  </div>
  <div class="field">
    <%= f.label :picture %>
    <%= f.file_field :picture %>
    <%= error_tag @room, :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/_review.html.erb
<section class="review">
  <% if room.show_form? %>
    <%= render partial: 'review_form', locals: { room: room } %>
  <% else %>
    <% room.stars.times do %>
      <span class="star filled-star"></span>
    <% end %>

    <% (room.review_points.max - room.stars).times do %>
      <span class="star empty-star"></span>
    <% end %>

    <%= t 'rooms.review.stats', count: room.total_reviews %>
  <% end %>
</section>

app/views/rooms/_review_form.html.erb
<% if room.can_review? %>
  <%= form_for room.review_route, remote: true do |f| %>
    <% room.review_points.each do |point| %>
      <%= f.radio_button :points, point, :checked => ( point == room.stars ? true : false ) %>
      <%= f.label :points, point, value: point do %>
        <i class="icon-star"></i>
      <% end %>
    <% end %>
    <%= f.submit %>
    <%= t 'rooms.review.stats', count: room.total_reviews %>
    <% if room.has_user_review? %>
      <p class="text-right user-review-info">
        <small><%= t 'layout.your_review_html', count: room.review.points %></small>
      </p>
    <% end %>
  <% end %>
<% else %>
  <span class="login-required">
    <%= t 'rooms.review.stats', count: room.total_reviews %>
  </span>
<% end %>

app/views/rooms/_room.html.erb
<div class="room-item">
  <hr />
  <% if room.kind_of?(RoomPresenter) %>
    <%= render partial: 'rooms/review', locals: { room: room } %>
  <% end %>
  <small class="created"><%= l room.created_at, format: :long %></small>
  <h2>
    #<%= room.id %> 
    <%= link_to highlight(room.title, @search_query), room_path(room) %>
    <small><%= highlight(room.location, @search_query) %></small>
    <em>, <%= t('layout.room_by_html', link: link_to(room.user.full_name, user_path(room.user)))  unless room.user.nil? %></em>
  </h2>
  <% if room.kind_of?(RoomPresenter) && room.has_picture? %>
    <figure><%= link_to image_tag(room.thumb_url), room.picture_url %></figure>
  <% end %>
  <blockquote><%= highlight(room.description || '', @search_query) %></blockquote>
  <% if belongs_to_user(room) || false %>
    <div class="actions">
      <%= link_to t('links.show'), room %> 
      <%= link_to t('links.edit'), edit_room_path(room) %> 
      <%= link_to t('links.destroy'), room, method: :delete, data: { confirm: t('messages.confirm') } %> 
    </div>
  <% end %>
  <div class="clear"></div>
</div>

app/views/rooms/_search.html.erb
<%= form_for rooms_path, method: :get, :html => { :class => 'search' } do %>
  <%= text_field_tag :q, @search_query, placeholder: t('.search_for') %>
  <%= button_tag '<i class="fa fa-search"></i>'.html_safe %>
<% end %>

app/views/rooms/edit.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form' %>

<%= link_to t('links.show'), @room %> |
<%= link_to t('links.back'), rooms_path %>

app/views/rooms/index.html.erb
<%= render 'search' %>

<h1>
  <% if @search_query.present? %>
    <%= t '.search_results', query: @search_query %>
  <% else %>
    <%= t '.title' %>
  <% end %>
</h1>

<%= show_notice notice %>

<%= render @rooms %>

<%= paginate @rooms %>

app/views/rooms/new.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form' %>

<%= link_to t('links.back'), rooms_path %>

app/views/rooms/show.html.erb
<h1><%= t 'layout.room_details' %></h1>

<%= show_notice notice %>

<%= render @room %>