config/routes.rb
Colchonet::Application.routes.draw do
  LOCALES ||= /en|es|pt\-BR/ 

  devise_for :admins
  
  # Site  
  scope "(:locale)", locale: LOCALES do
    resources :rooms do
      resources :reviews, only: [:create, :update], module: :rooms
    end
    resources :users
  end
  
  resource :confirmation, only: [:show]
  resource :user_sessions, only: [:create, :new, :destroy]

  get '/:locale' => 'homes#index', locale: LOCALES
  root 'homes#index'

  # Admin
  namespace :admin do
    resources :rooms
    resources :users, except: [:create, :new]
    get "about" => "dashboards#about"
    root to: "dashboards#index"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews, dependent: :destroy
  has_many :rooms, dependent: :destroy
  
  EMAIL_REGEX = /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
  
  validates :email, uniqueness: true, presence: true
  validates :full_name, presence: true
  validates :location, presence: true
  validates :bio, length: { minimum: 30 }

  has_secure_password

  scope :confirmed, -> { where.not(confirmed_at: nil) }
  
  validate do
    errors.add(:email, :invalid) unless email.match(EMAIL_REGEX)
  end

  before_create do |user|
    user.confirmation_token = SecureRandom.urlsafe_base64
  end

  def confirm!
    return if confirmed?

    self.confirmed_at = Time.current
    self.confirmation_token = ''
    save!
  end

  def confirmed?
    confirmed_at.present?
  end

  def self.authenticate(email, password)
    user = confirmed.
            find_by(email: email).
            try(:authenticate, password)
  end

  def name_for_select
    "##{self.id} - #{self.full_name}"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseAdminController
  before_action :set_admin_user, only: [:show, :edit, :update, :destroy]

  PER_PAGE = 10

  # GET /admin/users
  # GET /admin/users.json
  def index
    @admin_users = Admin::User.page(params[:page]).per(PER_PAGE)
  end

  # GET /admin/users/1
  # GET /admin/users/1.json
  def show
  end
  
  # GET /admin/users/1/edit
  def edit
  end

  # PATCH/PUT /admin/users/1
  # PATCH/PUT /admin/users/1.json
  def update
    respond_to do |format|
      if @admin_user.update(admin_user_params)
        format.html { redirect_to [:admin, @admin_user], notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.json
  def destroy
    @admin_user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_user
      @admin_user = Admin::User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_user_params
      params.require(:user).permit(:full_name, :email, :location, :bio)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  PER_PAGE = 10

  before_action :set_user, only: [:show, :edit, :update]
  before_action :can_change, only: [:edit, :update]
  before_action :require_no_authentication, only: [:new, :create]

  def show
    rooms = @user.rooms.page(params[:page]).per(PER_PAGE)
    @rooms = RoomCollectionPresenter.new(rooms.most_recent, self)
  end

  def edit
  end

  def update
    if @user.update(users_params)
      redirect_to @user, notice: "Cadastro atualizado com sucesso!"
    else
      render action: :edit
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
    if @user.save
      Signup.confirm_email(@user).deliver
      redirect_to root_path, notice: t('flash.notice.user_created')
    else
      render action: :new
    end
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def users_params
      params.
        require(:user).
        permit(:full_name, :location, :email, :password, :password_confirmation, :bio)
    end

    def can_change
      unless user_signed_in? && current_user == user
        redirect_to user_path(params[:id])
      end
    end

    def user
      @user ||= User.find(params[:id])
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for([:admin, @admin_user], :html_options => { :class => 'form' }) do |f| %>
  <% if @admin_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_user.errors.count, "error") %> prohibited this admin_user from being saved:</h2>

      <ul>
      <% @admin_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :full_name %><br>
    <%= f.text_field :full_name, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :location %><br>
    <%= f.text_field :location, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :bio %><br>
    <%= f.text_field :bio, :class => 'form-control' %>
  </div>
  <div class="form-group actions">
    <%= f.submit :class => 'btn btn-success' %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<div class="page-header">
	<h1><%= t('admin.editing_user') %></h1>
</div>
<%= breadcrumb %>

<%= render 'form' %>

<%= link_to '<i class="fa fa-search"></i> '.html_safe + t("admin.show"), @admin_user, { :class => 'btn btn-primary' } %> 
<%= back_link admin_users_path %>

app/views/admin/users/index.html.erb
<div class="page-header">
  <h1><%= t('admin.user') %></h1>
</div>
<%= breadcrumb %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t('admin.full_name') %></th>
      <th><%= t('admin.email') %></th>
      <th><%= t('admin.location') %></th>
      <th><%= t('admin.bio') %></th>
      <th><%= t('admin.actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% @admin_users.each do |admin_user| %>
      <tr>
        <td><%= admin_user.full_name %></td>
        <td><%= admin_user.email %></td>
        <td><%= admin_user.location %></td>
        <td><%= admin_user.bio %></td>
        <td>
          <%= show_link [:admin, admin_user] %>
          <%= edit_link edit_admin_user_path(admin_user) %>
          <%= destroy_link [:admin, admin_user] %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @admin_users %>

app/views/admin/users/new.html.erb
<div class="page-header">
	<h1><%= t('admin.new_user') %></h1>
</div>
<%= breadcrumb %>

<%= render 'form' %>

<%= back_link admin_users_path %>

app/views/admin/users/show.html.erb
<div class="page-header">
  <h1><%= t('admin.show_user') %></h1>
</div>
<%= breadcrumb %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @admin_user.full_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @admin_user.email %>
</p>

<p>
  <strong>Location:</strong>
  <%= @admin_user.location %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @admin_user.bio %>
</p>

<%= link_to t('admin.edit'), edit_admin_user_path(@admin_user), { :class => 'btn btn-success' } %> 
<%= back_link admin_users_path %>