config/routes.rb
Colchonet::Application.routes.draw do
  LOCALES ||= /en|es|pt\-BR/ 

  devise_for :admins
  
  # Site  
  scope "(:locale)", locale: LOCALES do
    resources :rooms do
      resources :reviews, only: [:create, :update], module: :rooms
    end
    resources :users
  end
  
  resource :confirmation, only: [:show]
  resource :user_sessions, only: [:create, :new, :destroy]

  get '/:locale' => 'homes#index', locale: LOCALES
  root 'homes#index'

  # Admin
  namespace :admin do
    resources :rooms
    resources :users, except: [:create, :new]
    get "about" => "dashboards#about"
    root to: "dashboards#index"
  end
end

app/views/layouts/_menu.html.erb
<div class="navbar-collapse collapse">
  <ul class="nav navbar-nav">
    <li class="hidden-xs hidden-sm divider-vertical"></li>
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= get_icon('plus') %> <%= t('site.new') %></a>
      <ul class="dropdown-menu">
        <% @plus_nav.each do |model| %>
          <li><%= link_to t( 'site.' + model.singularize ), send("new_admin_#{model.singularize}_path") %></li>
        <% end %>
      </ul>
    </li>
  </ul>
  <ul class="nav navbar-nav pull-right">
    <li><%= link_to( get_icon("off") + t("admin.logout") , destroy_admin_session_path , method: :delete) if admin_signed_in? %></li>
  </ul>
</div>

app/views/layouts/_user_navbar.html.erb
<ul>
  <li><%= link_to t('layout.create_room'), new_room_path %></li>
  <li><%= link_to t('layout.rooms'), rooms_path %></li>
  <li><%= link_to t('layout.my_profile'), user_path(current_user) %></li>
  <li><%= link_to t('layout.signout'), user_sessions_path, method: :delete %></li>
</ul>

app/views/layouts/_visitor_navbar.html.erb
<ul>
  <li><%= link_to t('layout.rooms'), rooms_path %></li>
  <li><%= link_to t('layout.signin'), new_user_sessions_path %></li>
</ul>

app/views/layouts/admin.html.erb
<!doctype html>
<html>
<head>
  <title><%= @meta_title %></title>
  <%= stylesheet_link_tag "//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css", media: "all" %>
  <%= stylesheet_link_tag    'admin/application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'admin/application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar-wrapper navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <div class="row">
        <div class="navbar navbar-inverse navbar-static-top" role="navigation">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <%= link_to @meta_title, "/admin", :class => "navbar-brand" %>
            </div>
            <%= render 'layouts/menu' %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-3 col-md-2 sidebar">
        <ul class="nav nav-sidebar">
          <% @nav.each do |item| %>
            <% @class_top_nav = if item["model"] == controller.controller_name then 'active' else '' end %>
            <li class="<%= @class_top_nav %>"><%= link_to get_icon(item["icon"]) + t( 'admin.' + item["model"] ), send("admin_#{item["model"]}_path", item["model"])  %></li>
          <% end %>
        </ul>
      </div>
      <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <%= yield %>
        <hr class="featurette-divider">
        <footer>
          <p class="pull-right">
            <a href="#"><%= t('admin.back_to_top') %></a>
          </p>
          <p>
            &copy; <%= Time.now.year %> <%= @meta_title %> 
            &middot; <%= link_to t('admin.about'), '/admin/about', { :data => { :toggle => 'modal', :target => '#mainModal' } } %>
          </p>
        </footer>
      </div>
    </div>
  </div>
  <div class="modal fade" id="mainModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/admin_login.html.erb
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Login</title>
  <%= stylesheet_link_tag "//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" %>
  <%= stylesheet_link_tag "admin/login" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Colcho.net</title>
  <link href='http://fonts.googleapis.com/css?family=Allura' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="page">
  <div class="wrapper-header wrapper-header-fixed">
    <header>
      <nav>
        <ul>
          <% [ {:"pt-BR" => "Português"}, {:es => "Spañol"}, {:en => "English"} ].each do |value| %>
            <li><%= link_to value.values.first.to_s, "/" + value.keys.first.to_s, :class => ( 'active' if locale.to_s == value.keys.first.to_s ) %></li>
          <% end %>
        </ul>
      </nav>
      <h1><%= link_to "Colcho.net", url_for( :controller => :homes, :action => :index ) %></h1>
    </header>
    <nav id="navbar-top">
      <% if user_signed_in? %>
        <%= render 'layouts/user_navbar' %>
      <% else %>
        <%= render 'layouts/visitor_navbar' %>
      <% end %>
    </nav>
  </div>
  <section class="container">
    <%= yield %>
  </section>
  <footer>
    <p><em>Colcho.net - Código aberto, licença GPL e MIT</em></p>
    <blockquote>
      <p>Ruby foi construído para tornar os programadores mais felizes.</p>
      <small>- Yukihiro "Matz" Matsumoto</small>
      <em>:D</em>
    </blockquote>
  </footer>
</div>
</body>
</html>